This is LBA package editor project file. Don't try to edit it by yourself unless you are absolutely sure what you are doing.
E:\Giery\LBA2\VOX\EN_GAM.VOX
E:\Giery\LBA2\VOX\EN_GAM-test.VOX
298
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam01.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam02.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam03.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam04.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam05.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam06.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam07.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam08.wav

E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam09.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam10.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam11.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam12.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam13.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam14.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam15.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam16.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam17.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam18.wav

E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam19.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam20.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam21.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam22.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam23.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam24.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam25.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam26.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam27.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam28.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam29.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam30.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam31.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam32.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam33.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam34.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam35.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam36.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam37.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam38.wav




E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam39.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam40.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam41.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam42.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam43.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam44.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam45.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam46.wav









































































































































































































































E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam47.wav
E:\Dodatki do gier\LBA\LBADeCOMP\Extract\2\en_gam\en_gam47_2.wav











